
# What should the plugin use to store it's data
# Supported: YAML
# Planned: MongoDB, MySQL, MariaDB
storage-type: YAML

# Should network features be enabled?
enable-network-features: false

# Used in network-wide notifications
server-name: global

# Communication serivce for network-wide features
redis:
  hostname: 127.0.0.1
  port: 6379
  username: default
  password: SUPER_SECRET_PASSWORD