
# What should the plugin use to store it's data
# Supported: YAML, MongoDB
# Planned: MariaDB
storage-type: YAML

# Should network features be enabled?
enable-network-features: false

# Used in network-wide notifications
server-name: global

# Communication service for network-wide features
redis:
  hostname: 127.0.0.1
  port: 6379
  username: default
  password: SUPER_SECRET_PASSWORD

# MongoDB credentials (Only required if using MongoDB storage type)
mongo:
  hostname: 127.0.0.1
  port: 27017
  username: default
  password: SUPER_SECRET_PASSWORD
  database: vitalutils