name: VitalUtilities

authors: [Pyr#6969]
version: ${version}

main: lol.pyr.utilities.UtilitiesPlugin
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  vitalutilities:
    aliases: [vital, utilities, vu]
    permission: utilities.admin
    permission-message: "You don't have the required permission to use this command"

  commandspy:
    aliases: [cspy, cs]
    permission: utilities.commandspy
    permission-message: "You don't have the required permission to use this command"

  gamemode:
    aliases: [gm]
    permission: utilities.gamemode
    permission-message: "You don't have the required permission to use this command"

  gms:
    aliases: [gm0]
    permission: utilities.gamemode
    permission-message: "You don't have the required permission to use this command"

  gmc:
    aliases: [gm1]
    permission: utilities.gamemode
    permission-message: "You don't have the required permission to use this command"

  gmsp:
    aliases: [gm3]
    permission: utilities.gamemode
    permission-message: "You don't have the required permission to use this command"

  gma:
    aliases: [gm2]
    permission: utilities.gamemode
    permission-message: "You don't have the required permission to use this command"

  clearinventory:
    aliases: [ci, clear, cls]
    permission: utilities.clearinventory
    permission-message: "You don't have the required permission to use this command"

  broadcast:
    aliases: [bc]
    permission: utilities.broadcast
    permission-message: "You don't have the required permission to use this command"

  networkbroadcast:
    aliases: [nbc, alert]
    permission: utilities.networkbroadcast
    permission-message: "You don't have the required permission to use this command"

  togglestaffnotifications:
    aliases: [togglenotifs, notifs]
    permission: utilities.staffnotifications
    permission-message: "You don't have the required permission to use this command"

  heal:
    permission: utilities.heal
    permission-message: "You don't have the required permission to use this command"

  feed:
    permission: utilities.feed
    permission-message: "You don't have the required permission to use this command"

  fly:
    permission: utilities.fly
    permission-message: "You don't have the required permission to use this command"

  sudo:
    permission: utilities.sudo
    permission-message: "You don't have the required permission to use this command"

  tpall:
    permission: utilities.tpall
    permission-message: "You don't have the required permission to use this command"

permissions:
  utilites.clearinventory.others:
    description: "Allows players to clear other player's inventories with the /clearinventory command"

  utilites.gamemode.others:
    description: "Allows players to switch other player's gamemode with the /gamemode command"

  utilities.feed.others:
    description: "Allows players to heal other players with the /feed command"

  utilities.heal.others:
    description: "Allows players to feed other players with the /heal command"